coordinator:
  strategy: plan-execute #options: react, plan-execute
  model_id: meta-llama/Meta-Llama-3-70B-Instruct
  llm_endpoint_url: http://${host_ip1}:${port1}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: true
  is_coordinator: true
  role_description: "The coordinator is responsible for managing the conversation flow and ensuring that the conversation is coherent and on-topic. The coordinator will also ensure that the conversation is engaging and that the user's needs are met."
  tools: coordinator_tools.yaml

researcher:
  strategy: react
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  is_coordinator: false
  role_description: "The researcher is responsible for providing accurate and relevant information to the user. The researcher will use the latest research and data to answer the user's questions and provide valuable insights."
  tools: researcher_tools.yaml

writer:
  strategy: react 
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  is_coordinator: false
  role_description: "The writer is responsible for generating engaging and informative content for the user. The writer will use the latest research and data to create compelling narratives and stories that captivate the user's attention."
  tools: none


reviewer:
  strategy: react
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  is_coordinator: false
  role_description: "The reviewer is responsible for ensuring the quality and accuracy of the content generated by the writer. The reviewer will review the content and provide feedback to the writer to improve the quality of the output."
  tools: reviewer_tools.yaml