coordinator:
  strategy: plan-execute #options: react, plan-execute
  model_id: meta-llama/Meta-Llama-3-70B-Instruct
  llm_endpoint_url: http://${host_ip1}:${port1}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: true
  level: 1
  role_description: "The coordinator is responsible for managing the conversation flow and ensuring that the conversation is coherent and on-topic. The coordinator will also ensure that the conversation is engaging and that the user's needs are met."
  tools: coordinator_tools.yaml


market_research_manager:
  strategy: react
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  level: 2
  role_description: "The market research manager is responsible for conducting market research and analysis to identify trends and opportunities in the market. The market research manager will use the latest data and insights to inform business decisions and strategies."
  tools: market_research_manager_tools.yaml

researcher:
  strategy: react
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  level: 3
  role_description: "The researcher is responsible for providing accurate and relevant information to the user. The researcher will use the latest research and data to answer the user's questions and provide valuable insights."
  tools: researcher_tools.yaml

writer:
  strategy: react 
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  level: 3
  role_description: "The writer is responsible for generating engaging and informative content for the user. The writer will use the latest research and data to create compelling narratives and stories that captivate the user's attention."
  tools: none


reviewer:
  strategy: react
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  level: 3
  role_description: "The reviewer is responsible for ensuring the quality and accuracy of the content generated by the writer. The reviewer will review the content and provide feedback to the writer to improve the quality of the output."
  tools: reviewer_tools.yaml

campaign_manager:
  strategy: react
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  level: 2
  role_description: "The campaign manager is responsible for planning and executing marketing campaigns to promote products and services. The campaign manager will use the latest marketing strategies and techniques to reach target audiences and achieve business objectives."
  tools: campaign_manager_tools.yaml

event_planner:
  strategy: react
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  level: 3
  role_description: "The event planner is responsible for organizing and coordinating events to promote products and services. The event planner will work with vendors and suppliers to ensure that events are successful and meet business objectives."
  tools: event_planner_tools.yaml

social_media_agent:
  strategy: react
  model_id: mistralai/Mistral-7B-Instruct-v0.3
  llm_endpoint_url: http://${host_ip2}:${port2}/v1/chat/completions
  llm_engine: tgi #options: tgi, vllm, openai
  recursion_limit: 20
  require_human_feedback: false
  level: 3
  role_description: "The social media agent is responsible for managing social media accounts and engaging with followers to promote products and services. The social media agent will use the latest social media trends and strategies to reach target audiences and increase brand awareness."
  tools: social_media_agent_tools.yaml