NAME=ragtool-xeon-backend-server
PORT=8889
export MEGA_SERVICE_HOST_IP=${host_ip}
export MEGA_SERVICE_NAME=ragtool # NEED TO CHANGE ACCORDING TO MEGA SERVICE!!!
export MEGA_SERVICE_PORT=8889 # NEED TO CHANGE ACCORDING TO MEGA SERVICE!!!
# export BACKEND_SERVICE_ENDPOINT="http://${host_ip}:${MEGA_SERVICE_PORT}/v1/${MEGA_SERVICE_NAME}"
export EMBEDDING_SERVICE_HOST_IP=${host_ip}
export RETRIEVER_SERVICE_HOST_IP=${host_ip}
export RERANK_SERVICE_HOST_IP=${host_ip}
export LLM_SERVICE_HOST_IP=${host_ip}

docker run -it --name=$NAME \
-p $PORT:$PORT \
--ipc=host \
-e http_proxy=$http_proxy \
-e https_proxy=$https_proxy \
-e MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP} \
-e MEGA_SERVICE_PORT=${MEGA_SERVICE_PORT} \
-e EMBEDDING_SERVICE_HOST_IP=${EMBEDDING_SERVICE_HOST_IP} \
-e RETRIEVER_SERVICE_HOST_IP=${RETRIEVER_SERVICE_HOST_IP} \
-e RERANK_SERVICE_HOST_IP=${RERANK_SERVICE_HOST_IP} \
-e LLM_SERVICE_HOST_IP=${LLM_SERVICE_HOST_IP} opea/ragtool:latest\
